version: "3"
services:
  wss:
    container_name: "traefik_example_wss"
    build:
      context: ./wss/
    expose:
      - 8081
      - 8082
    volumes:
      - ./wss:/home/wss:ro
    command: python main.py & && python main2.py
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.wss.rule=Host(`oligami.ml`)&&(Path(`/wss/traefik_example/`))
      - traefik.http.routers.wss.tls=true
      - traefik.http.routers.wss.tls.certresolver=myresolver

      - traefik.http.routers.wss.entrypoints=tls8081,tls8082

  wss2:
    container_name: "traefik_example_wss2"
    build:
      context: ./wss/
    expose:
      - 8082
    ports:
      - 53005:8081
    volumes:
      - ./wss:/home/wss:ro
    command: python main.py & && python main2.py
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.wss2.rule=Host(`oligami.ml`)&&(Path(`/wss/traefik_example2/`))
      - traefik.http.routers.wss2.tls=true
      - traefik.http.routers.wss2.tls.certresolver=myresolver

      - traefik.http.routers.wss2.entrypoints=tls8082

  webserver:
    image: nginx:alpine
    container_name: traefik_example_webpage
    restart: always
    volumes:
      - ./server/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server/log:/var/log/nginx
      - ./server/html:/var/www/html/traefik_example:ro
    networks:
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik_example_webpage.entrypoints=web-secure
      - traefik.http.routers.traefik_example_webpage.rule=Host(`oligami.ml`)&&(PathPrefix(`/traefik_example/`)||Path(`/link/7iMsf0`))
      - traefik.http.routers.traefik_example_webpage.tls=true
      - traefik.http.routers.traefik_example_webpage.tls.certresolver=myresolver

      - traefik.http.middlewares.pathsetup.replacepathregex.regex=^/(link)/([^/]*)
      - traefik.http.middlewares.pathsetup.replacepathregex.replacement=/$${1}/$${2}/
      - traefik.http.routers.traefik_example_webpage.middlewares=pathsetup@docker

networks:
  traefik-net:
    external: true
