# Providers config
# log:
#   level: DEBUG

providers:
  docker: # Enable tells treafik to listen to docker
    exposedByDefault: false
    network: traefik-net

  file:
    directory: /etc/traefik/dynamic

# API/Dashboard config
api:
  insecure: true # Enable the Web UI

experimental:
  http3: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https

  web-secure:
    address: :443

  tls8081:
    address: :8081

  tls8082:
    address: :8082

certificatesResolvers:
  myresolver:
    acme:
      email: hogehoge@gmail.com
      storage: /letsencrypt/default/acme.json
      tlsChallenge: {}
      # caserver: 'https://acme-staging-v02.api.letsencrypt.org/directory'
      # httpChallenge:
      #   entryPoint: web